### ISSUE TITLE
Set Up GitHub Actions 

### ISSUE THREAD

**Issue by Ali-Almadhagi** [Ali-Almadhagi/MiniCanvas#3]
**User Story**
As a developer,
I want a continuous integration pipeline set up using GitHub Actions,So that all commits and pull requests are automatically tested to ensure they meet our quality standards before merging.

**Description**
Implement a GitHub Actions workflow to automatically test all code pushed to main and development branches, ensuring that every contribution meets quality standards before merging.

**Tasks**

- [ ] Set Up Workflow Configuration
- [ ] Implement Testing Pipeline
- [ ] Ensure Workflow Validation
